### ISSUE TITLE
support for enum de-/serialization with ordinal

### ISSUE THREAD

**Issue by ubhaller** [Ubique-OSS/springboot-swagger3#13]
ability to specify when ordinals are used for enum de-/serialization. expected swagger output would be something like:

```yaml
Color:
  type: integer
  format: int32
  enum:
  - 0
  - 1
  - 2
  x-enum-varnames:
  - RED
  - BLUE
  - GREEN
```
